# Generated by Django 2.2.4 on 2019-12-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pageid', models.IntegerField(blank=True, db_column='pageId', null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='CategoryInlinks',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('inlinks', models.IntegerField(blank=True, db_column='inLinks', null=True)),
            ],
            options={
                'db_table': 'category_inlinks',
            },
        ),
        migrations.CreateModel(
            name='CategoryOutlinks',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('outlinks', models.IntegerField(blank=True, db_column='outLinks', null=True)),
            ],
            options={
                'db_table': 'category_outlinks',
            },
        ),
        migrations.CreateModel(
            name='CategoryPages',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pages', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category_pages',
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('disambiguationcategory', models.CharField(blank=True, db_column='disambiguationCategory', max_length=255, null=True)),
                ('maincategory', models.CharField(blank=True, db_column='mainCategory', max_length=255, null=True)),
                ('nrofpages', models.BigIntegerField(blank=True, db_column='nrofPages', null=True)),
                ('nrofredirects', models.BigIntegerField(blank=True, db_column='nrofRedirects', null=True)),
                ('nrofdisambiguationpages', models.BigIntegerField(blank=True, db_column='nrofDisambiguationPages', null=True)),
                ('nrofcategories', models.BigIntegerField(blank=True, db_column='nrofCategories', null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'MetaData',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pageid', models.IntegerField(blank=True, db_column='pageId', null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('isdisambiguation', models.TextField(blank=True, db_column='isDisambiguation', null=True)),
            ],
            options={
                'db_table': 'Page',
            },
        ),
        migrations.CreateModel(
            name='PageCategories',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pages', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'page_categories',
            },
        ),
        migrations.CreateModel(
            name='PageInlinks',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('inlinks', models.IntegerField(blank=True, db_column='inLinks', null=True)),
            ],
            options={
                'db_table': 'page_inlinks',
            },
        ),
        migrations.CreateModel(
            name='Pagemapline',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('pageid', models.IntegerField(blank=True, db_column='pageID', null=True)),
                ('stem', models.CharField(blank=True, max_length=255, null=True)),
                ('lemma', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'PageMapLine',
            },
        ),
        migrations.CreateModel(
            name='PageOutlinks',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('outlinks', models.IntegerField(blank=True, db_column='outLinks', null=True)),
            ],
            options={
                'db_table': 'page_outlinks',
            },
        ),
        migrations.CreateModel(
            name='PageRedirects',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('redirects', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'page_redirects',
            },
        ),
    ]
